version: '3'

services:
  spark-master:
    image: guthman_arm64/spark:3.1.2
    container_name: spark_master
    restart: unless-stopped
    hostname: spark
    environment:
        - SPARK_MODE=master
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
    expose:
      - 8080
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
        - ./spark/app:/usr/local/spark/app  # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
        - ./spark/resources:/usr/local/spark/resources  # Resources folder (Must be the same path in airflow and Spark Cluster)

  spark-worker-1:
    image: guthman_arm64/spark:3.1.2
    container_name: spark_worker1
    restart: unless-stopped
    environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark:7077
        - SPARK_WORKER_MEMORY=6G
        - SPARK_WORKER_CORES=1
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
    expose:
      - 8081
    ports:
      - "8081:8081"
    volumes:
        - ./spark/app:/usr/local/spark/app  # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
        - ./spark/resources:/usr/local/spark/resources  # Resources folder (Must be the same path in airflow and Spark Cluster)