version: '3'

services:
  spark-master:
    image: guthman_arm64/spark:3.1.2
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    container_name: spark_master
    platform: linux/arm64
    restart: unless-stopped
    user: root # Run container as root container: https://docs.bitnami.com/tutorials/work-with-non-root-containers/
    hostname: spark_master
    environment:
        - SPARK_MODE=master
        - MASTER=spark://master:7077
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
        - SPARK_PUBLIC_DNS=localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
    volumes:
        - ./spark/app:/usr/local/spark/app  # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
        - ./spark/resources:/usr/local/spark/resources  # Resources folder (Must be the same path in airflow and Spark Cluster)

  spark-worker-1:
    image: guthman_arm64/spark:3.1.2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    container_name: spark_worker1
    platform: linux/arm64
    restart: unless-stopped
    user: root
    hostname: spark_worker1
    environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark:7077
        - SPARK_WORKER_MEMORY=1G
        - SPARK_WORKER_CORES=1
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
        - SPARK_WORKER_PORT=8881
        - SPARK_WORKER_WEBUI_PORT=8081
        - SPARK_PUBLIC_DNS=localhost
    links:
        - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - "8081:8081"
    volumes:
        - ./spark/app:/usr/local/spark/app  # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
        - ./spark/resources:/usr/local/spark/resources  # Resources folder (Must be the same path in airflow and Spark Cluster)